services:

  tempo:
    image: grafana/tempo:latest
    container_name: incident-tempo
    command: [ "-config.file=/etc/tempo.yml" ]
    ports:
      - "3200:3200"
      - "4318:4318"
    networks:
      - incident-net
    volumes:
      - ./monitoring/tempo/tempo.yml:/etc/tempo.yml
      - tempo-data:/var/tempo
  keycloak:
    container_name: KEYCLOAK_CONTAINER
    image: quay.io/keycloak/keycloak:26.2.5
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}

      KC_DB_POOL_INITIAL_SIZE: 1
      KC_DB_POOL_MIN_SIZE: 1
      KC_DB_POOL_MAX_SIZE: 3
    volumes:
      - ./my-keycloak-theme:/opt/keycloak/themes
      - ./realm-config:/opt/keycloak/data/import
    ports:
      - "8080:8080"
    networks:
      - incident-net
    restart: unless-stopped

  incident-postgres:
    container_name: INCIDENT_CONTAINER
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: incident
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - postgres-incident:/var/lib/postgres/data
    networks:
      incident-net:
    ports:
      - "5432:5432"
    restart: unless-stopped

  notification-postgres:
    container_name: NOTIFICATION_CONTAINER
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: notification
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - postgres-incident:/var/lib/postgres/data
    networks:
      incident-net:
    ports:
      - "3456:5432"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: incident-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    container_name: incident-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus



  mail-dev:
    container_name: ms_mail_dev2
    image: maildev/maildev
    ports:
      - "7896:1080"
      - "2346:1025"

  loki:
    image: grafana/loki:latest
    container_name: incident-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./monitoring/loki/loki-config.yml:/etc/loki/loki-config.yml
      - loki-data:/loki

  alloy:
    image: grafana/alloy:latest
    container_name: incident-alloy
    ports:
      - "12345:12345"
    volumes:
      - ./monitoring/alloy/config.alloy:/etc/alloy/config.alloy
      - ./logs:/var/log/incident-manager:ro
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
    depends_on:
      - loki
  kafka:
    image: apache/kafka-native
    ports:
      - "9092:9092"
    environment:
      # Configure listeners for both docker and host communication
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT

      # Settings required for KRaft mode
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091

      # Listener to use for broker-to-broker communication
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

      # Required for a single node cluster
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      incident-net:


networks:
  incident-net:
    driver: bridge
volumes:
  postgres-incident:
  kafka-data:
  prometheus-data:
  grafana-data:
  loki-data:
  tempo-data: