spring:
  application:
    name: notification-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:create}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: ${JPA_SHOW_SQL:false}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:notification-service-group}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT:2346}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp: "*"
      auth: true
      starttls:
        enable: true

server:
  port: ${SERVER_PORT:2345}

jwt:
  auth:
    converter:
      principal-attribute: ${JWT_PRINCIPAL_ATTRIBUTE:preferred_username}

management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:health,info}

otel:
  service:
    name: ${OTEL_SERVICE_NAME}
  traces:
    exporter: console
  metrics:
    exporter: none
  logs:
    exporter: none

logging:
  file:
    name: ${LOG_FILE_PATH}
  level:
    root: INFO