spring:
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations: classpath:db/migration
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:false}
    baseline-version: ${FLYWAY_BASELINE_VERSION:0}
  application:
    name: incident-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: ${JPA_SHOW_SQL:false}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"

    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:group1}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.manage.incident_service.failures"
        spring.json.value.default.type: "com.manage.incident_service.failures.FailureRecord"
        spring.json.use.type.headers: false

server:
  port: ${SERVER_PORT:6567}

jwt:
  auth:
    converter:
      principal-attribute: ${JWT_PRINCIPAL_ATTRIBUTE:preferred_username}

otel:
  service:
    name: ${OTEL_SERVICE_NAME}
  traces:
    exporter: otlp
  metrics:
    exporter: none
  logs:
    exporter: none
  exporter:
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}
      protocol: ${OTEL_EXPORTER_OTLP_PROTOCOL:http/protobuf}


management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS}
logging:
  file:
    name: ${LOG_FILE_PATH}
  level:
    root: INFO